name: habit_tracker
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  date_picker_timeline: any
  cupertino_icons: ^1.0.2
  getwidget: ^3.0.1
  curved_navigation_bar: ^1.0.3
  animated_notch_bottom_bar: ^0.0.6
  table_calendar: any
  pie_chart: ^5.3.2
  fl_chart: ^0.55.2
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_core: ^2.4.1
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - Assets/images/bg.jpg

  fonts:
    - family: Quicksand
      fonts:
        - asset: Assets/fonts/Quicksand-Regular.ttf
